// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Models;

#nullable disable

namespace QuanLyKho.Migrations
{
    [DbContext(typeof(QuanLyKhoContext))]
    [Migration("20251202050721_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKho.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("QuanLyKho.Models.Employee", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNV");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("QuanLyKho.Models.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatNCC")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhachDat")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("QuanLyKho.Models.KhoHang", b =>
                {
                    b.Property<int>("KhoHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoHangId"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhoHangId");

                    b.ToTable("KhoHangs");
                });

            modelBuilder.Entity("QuanLyKho.Models.NCC", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("NoHienTai")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongMua")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhapHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.ToTable("NhapHangs");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<decimal>("TongGiaTri")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuat", b =>
                {
                    b.Property<string>("MaPX")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("date");

                    b.Property<decimal>("TongGiaTri")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaPX");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhapHang", b =>
                {
                    b.HasOne("QuanLyKho.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKho.Models.NCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Models.Employee", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKho.Models.NCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Models.Employee", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
